variables:
  - name: baseUrl
    value: https://staging.deshifishery.com
    type: string
  - name: apiVersion
    value: v1
    type: string
  - name: pondId
    value: ''
    type: string
  - name: stockReleaseId
    value: ''
    type: string
